# Generated by Django 3.0.5 on 2020-04-21 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'samochód',
                'verbose_name_plural': 'samochody',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('number', models.CharField(help_text='Wprowadz nr czesci w formacie 0X0000000XX', max_length=14, unique=True, verbose_name='numer')),
                ('car', models.ManyToManyField(to='order.Car')),
            ],
            options={
                'verbose_name': 'część',
                'verbose_name_plural': 'części',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='numer')),
                ('description', models.TextField(verbose_name='opis')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Car')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problemy',
            },
        ),
        migrations.CreateModel(
            name='PartStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10, verbose_name='stan')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Part')),
            ],
            options={
                'verbose_name': 'stan generacyjny częśći',
                'verbose_name_plural': 'stany generacyjne częśći',
                'unique_together': {('part', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique_for_year='date_time_delivery', verbose_name='numer')),
                ('amount_part', models.IntegerField(default=1, help_text='Wprowadz liczbe mierzonych czesci', verbose_name='liczba części')),
                ('date_time_delivery', models.DateTimeField(verbose_name='data dostarczenia')),
                ('date_time_collect', models.DateTimeField(blank=True, null=True, verbose_name='data odbioru')),
                ('knnr', models.IntegerField(blank=True, help_text='Wprowadz nr w formacie 0000000', null=True)),
                ('measuring_specification', models.TextField(verbose_name='specyfikacja pomiaru')),
                ('measuring_reason', models.TextField(verbose_name='powód pomiaru')),
                ('production_stage', models.IntegerField(choices=[(0, 'Serie'), (1, '0-serie'), (2, 'PVS'), (3, 'Versuch')], default=False, verbose_name='etap produkcyjny')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ManyToManyField(to='order.PartStage')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.Problem')),
            ],
            options={
                'verbose_name': 'zlecenie',
                'verbose_name_plural': 'zlecenia',
            },
        ),
    ]
